repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 6e2418c5521b7d606e72914dced3253f9ace1205  # frozen: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: e66be67b9b6811913470f70c28b4d50f94d05b22  # frozen: 20.8b1
    hooks:
    -   id: black

# https://pycqa.github.io/isort/docs/configuration/pre-commit/
-   repo: https://github.com/pycqa/isort
    rev: 473d150c1db60f4614a574e30993e9e0d3ca0cce  # frozen: 5.7.0
    hooks:
    - id: isort
      name: isort (python)
